server:
  port: 19101
spring:
  application:
    name: college-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://genuniv-db:5432/genuniv_college
    username: postgres
    password: password
    maximum-pool-size: 50
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
intra:
  service:
    GeneralInfo:
      protocol: http
      service-name: general-info-service
      SchoolYearAPI:
        api-prefix: /api/v1/school-year
      SchoolPeriodAPI:
        api-prefix: /api/v1/school-period
      ScheduleAPI:
        api-prefix: /api/v1/schedule
    PersonalRecords:
      protocol: http
      service-name: personal-records-service
      FacultyAPI:
        api-prefix: /api/v1/faculty
loading-cache:
  slow-interval: 30
  fast-interval: 15
